### ISSUE TITLE
Move "client" out of haas.cfg to somewhere less icky

### ISSUE THREAD

**Issue by ryabouza** [CCI-MOC/haas#194]
I noticed that running "project_apply" from anywhere other than the directory containing 'haas.cfg' causes the client to spit out a "ConfigParser.NoSectionError: No section: 'client'" error.  The 'client' information should probably be stored in a different configuration in a more sensible location.

**Comment by henn** [comment]
This can be done via setting the `HAAS_ENDPOINT` env variable now.
