### ISSUE TITLE
test_isolated_networks bug

### ISSUE THREAD

**Issue by ryabouza** [CCI-MOC/haas#242]
There is a bug in the deployment tests that will cause test_isolated_networks to incorrectly pass/fail sometimes.  The bug is in ```get_network()``` when it runs ```if intfc in vlan_cfg:```.  

This will return true when ```intfc``` is ```gi1/0/1``` and ```vlan_cfg``` contains ```gi1/0/18```.  

Also, ```vlan_cfg``` lists sequential ports using a range, which could cause the test to incorrectly pass OR fail when a particular value is not found because it is in a range (e.g. ```gi1/0/2 in gi1/0/1-3``` would return ```False```.

**Comment by zenhack** [comment]
Note: #408 completely changes how the switch is queried, so this will be obsolete when that's merged.
