### ISSUE TITLE
Query API extensions

### ISSUE THREAD

**Issue by gsilvis** [CCI-MOC/haas#257]
We're missing some pretty clearly useful stuff right now:  for instance, 'get_networks_in_project'.

**Comment by henn** [comment]
@gsilvis: is there anything left for this request that isn't covered by #453?

**Comment by gsilvis** [comment]
@henn: Either way, I think the other bug better captures what's going on then this one.  Unless you think there's information that belongs here and not there, let's close this bug.  (Finally.)
