### ISSUE TITLE
Handle multiple switches

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#327]
This was contained in docs/multiple-switches.md, which I'm about to clean up.

Tossing this in here for future work:
    At some point or another we're going to want to deal with nodes on multiple
    switches. Depending on the situation, we plan to handle this in one of two
    ways:
 
    1. Stack the switches -- if all of the switches are the same, it's
       typically possible to daisy-chain them together, and treat them as
       one switch. It's easy enough for us to support this without invasive
       changes to our existing code.
    2. Shell out to a driver which deals with the complexity for us, e.g.
       OpenDaylight.

**Comment by zenhack** [comment]
the complex vlan driver has been merged, closing.

**Comment by henn** [comment]
@gsilvis, just wanted to make sure we weren't losing any state with the
deleting of that documentation. I agree that complex_vlan addresses the
issue so this should stay closed. Thanks


> @henn Did you have something in mind other than what @zenhack just said?
