### ISSUE TITLE
Need a list_projects call for admins & devs

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#355]
Admins may want to list projects so that they can track down allocated nodes without manually looking through the DB.

Developers may want to look for a random node name to run commands on or may have forgotten what project name they may have used.

**Comment by zenhack** [comment]
How about we just grab 02673c8 and add some tests? The rest of the pull request might require a bit more scrutiny, but I think that commit looks pretty solid.

//cc @henn, @gsilvis, @lokI8

**Comment by zenhack** [comment]
This was resolved by #424; closing.
