### ISSUE TITLE
Need upstart/systemd script for haas serve_networks

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#364]
The install doc currently says to run:
    haas serve_networks &

This means that we're depending on the user's terminal to host a long-lived process. We should provide a startup script to run the daemon in the background. CentOS 6 supports upstart, CentOS 7 is systemd.

**Comment by henn** [comment]
The output should also get recorded somewhere. Currently, it's not so if the daemon dies you have to guess why (unless it reproducibly keeps dying :)

**Comment by zenhack** [comment]
Quoting henn (2015-07-25 02:00:29)

>    The output should also get recorded somewhere. Currently, it's not so
>    if the daemon dies you have to guess why (unless it reproducibly keeps
>    dying :)

Systemd captures stdout/stderr by default, so writing a service script
for it would do the trick on systemd based systems.

**Comment by henn** [comment]
FYI - `serve_networks` seems to die sometimes on some haas installs. This feature would make it much easier to debug!

**Comment by henn** [comment]
Closed by #525
