### ISSUE TITLE
Merge moc-rest into haas repo

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#394]
Currently, installing HaaS requires a separate install step for the moc-rest module. There is some agreement within the team that merging moc-rest back into HaaS would simplify the installation and maintenance process and make certain development tasks (especially decorators) easier to implement.

Here are some links that might help with maintaining the history (if that's important):
* http://jasonkarns.com/blog/merge-two-git-repositories-into-one/
* https://www.kernel.org/pub/software/scm/git/docs/git-fast-import.html
* http://bpeirce.me/moving-one-git-repository-into-another.html

**Comment by zenhack** [comment]
This has been done, closing.
