### ISSUE TITLE
Can't list project through the REST api call

### ISSUE THREAD

**Issue by haydarkarrar** [CCI-MOC/haas#401]
There is no api call for this

**Comment by zenhack** [comment]
#362 adds one. @ryabouza isn't working with us anymore does anyone else want to volunteer to fix this up?

//cc @gsilvis, @lokI8

**Comment by SahilTikale** [comment]
I realized that while working on rHaaS project. I have included that as one of the items in our backlog.
So if it is not urgent, our team would like to contribute that.

**Comment by haydarkarrar** [comment]
Can you check the pull requests #405 ? I added the project listing and getting project's headnode functionality

**Comment by zenhack** [comment]
Closing this; a solution has been merged.
