### ISSUE TITLE
Can't attach node to the project by API call

### ISSUE THREAD

**Issue by haydarkarrar** [CCI-MOC/haas#402]
We need to specify which node we want to attach or detach.

Please look at @rest_call('POST', '/project/<project>/connect_node') in haas/api.py file

**Comment by zenhack** [comment]
The node name goes in the body of the request, in a JSON object, e.g.:

    {"node": "node-4"}

This is generally true of any parameters that aren't in the URL. See `docs/rest_api.md` for a reference (It's terse, but at least has the full mapping).

I'm going to close this issue; the needed functionality already exists.
