### ISSUE TITLE
serve_networks is intended to apply network operations in order, but doesn't

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#420]
70c2aad2 indended to ensure that network operations are applied in-order. Note that there's some discussion amongst the team about whether this is what we want, but the code is actually incorrect; the operations are used to build up a dictionary, which is an unordered data structure. If we're going to keep the indented behavior, we should use a sequential datastructure here.

**Comment by henn** [comment]
Fixing #314 would address this.

**Comment by zenhack** [comment]
#455 reworks how serve_network does things, and in the process addresses this issue. Once that's merged, we can close this.

**Comment by zenhack** [comment]
#455 has been merged, closing.
