### ISSUE TITLE
Get HaaS working with PostgreSQL

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#428]
We need support for a production ready DBMS (sqlite isn't even thread-safe). Postgres should be pretty easy to get working; *in theory* it should work already, but is untested so there are probably going to be a few snags to fix.

**Comment by apoorvemohan** [comment]
I have completed the changes but I need to test it. I see a tests directory in the haas code. Can anyone  guide me how to use them.

**Comment by apoorvemohan** [comment]
Tested on Centos 6.6. Will create a pull request after testing on Centos 7 (on PRB cluster).

**Comment by zenhack** [comment]
This has been fixed in master; closing.
