### ISSUE TITLE
HaaS ipmi driver needs -I lanplus to work with nexus switch

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#438]
I haven't yet read up on what this option actually does. We should figure that out, and decide if we ever need to not pass it. If so, a proper solution may have to wait for @SahilTikale's OBM driverization.

**Comment by zenhack** [comment]
Apparently this is basically a different wire protocol that adds things like encryption and better integrity checking. It's also IPMI 2-only, which means the sunfires we have in prb won't work with it.

I'm inclined to suggest just adding in as a default anyway; I don't think we really care all that much about the sun blades. Once @apoorvemohan and @SahilTikale finish drivertizing the OBMs, if we really want it we can write an IPMI 1.5 driver.

@gsilvis, @lokI8, thoughts?

**Comment by pjd-nu** [comment]
If we need test machines in PRB, we still have the Supermicro boxes. I assume they're IPMI 2.

> On Jul 15, 2015, at 10:00 PM, Ian Denhardt <notifications@github.com> wrote:
> Apparently this is basically a different wire protocol that adds things like encryption and better integrity checking. It's also IPMI 2-only, which means the sunfires we have in prb won't work with it.
> 

.....................................................................
 Peter Desnoyers                                  pjd@ccs.neu.edu
 Northeastern Computer & Information Science      (617) 373-8683

**Comment by zenhack** [comment]
Quoting Peter Desnoyers (2015-07-16 07:39:30)

>    If we need test machines in PRB, we still have the Supermicro boxes. I
>    assume they're IPMI 2.

Yeah, that was my thinking.
