### ISSUE TITLE
node_delete doesn't check if the node has nics

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#443]
If it does, sqlalchemy throws an exception (because the `owner_id` column in `Nic` is not nullable).

We should check this and throw a `BlockedError` (which I think is most consistent with the rest of HaaS' behavior.

**Comment by gsilvis** [comment]
Agree with sol'n

**Comment by zenhack** [comment]
Okay, I'm going to take discuss off of this and submit a fix.
