### ISSUE TITLE
(incoming) dev_support test fails sometimes for strange reasons

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#448]
This is on my refactoring branch, but I'm not getting to it soon and don't want to forget about it:
The first test in dev_support sometimes spits out the following error:

```
============================================== ERRORS ===============================================
________________________________ ERROR at setup of testsuite_config _________________________________
file /home/isd/work/haas/haas/test_common.py, line 23
  def testsuite_config():
        fixture 'configure' not found
        available fixtures: pytestconfig, cov, recwarn, monkeypatch, capfd, capsys, tmpdir
        use 'py.test --fixtures [testpath]' for help on them.

/home/isd/work/haas/haas/test_common.py:23
```
This seems to depend on what tests are run; if just the dev_support tests are run it works fine. When all of tests/unit is run however, the error occurs.

**Comment by gsilvis** [comment]
The problem is that 'testsuite_config' starts with 'test'.  I don't quite understand how it's getting picked up by py.test, nor why doing multiple tests change it, but it's definitely the problem.

**Comment by zenhack** [comment]
That is *so* dumb. Nice catch.

**Comment by zenhack** [comment]
Closing, since @gsilvis fixed this.
