### ISSUE TITLE
Database session should be request-local

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#454]
This would simplify a large portion of the control flow. Even in spite of the refactoring changes I'm doing, it's still a little awkward to get at the session. The session could be created in `haas.rest`.

@gsilvis?

**Comment by gsilvis** [comment]
Seems like a good idea to me

**Comment by zenhack** [comment]
Just a note @apoorvemohan has discovered a resouce leak related to this (we're not closing database connections somewhre, which doesn't suprprise me). I'm disinclined to spend much effort hunting that down; I'd rather just address this and have all of the creation/deletion in one place.

**Comment by henn** [comment]
FYI - this is being hit in our production setup.

To address it for now, I increased the number of processes. Going forward, I think we all agree that HaaS should follow [SQLAlchemy's advice](http://docs.sqlalchemy.org/en/rel_0_9/orm/session_basics.html) and explicitly close them as part of the framework.

**Comment by zenhack** [comment]
@henn, can you give me an estimate of how frequently you were hitting the error before bumping up the number of processes (and how many processes there were), and roughly how many requests per unit time it was servicing? I'm trying to estimate what it's going to take to reproduce this reliably.

**Comment by henn** [comment]
I only know of one instance of hitting it. We had 25 threads and 1 WSGI process before, so I reduced the number of threads (to something like 4) and increased the processes.

Looking at the list_* functions, I think the issue is that we don't have a db.commit() or db.close() at the end, so we have to wait until the local vars are garbage collected for the session to be closed out. When someone does a bunch of these in succession and there are plenty of threads to service it, my guess is that gc doesn't happen quickly enough:
```python
@rest_call('GET', '/project/<project>/nodes')
def list_project_nodes(project):
    """List all nodes belonging the given project.

    Returns a JSON array of strings representing a list of nodes.

    Example:  '["node1", "node2", "node3"]'
    """
    db = model.Session()
    project = _must_find(db, model.Project, project)
    nodes = project.nodes
    nodes = [n.label for n in nodes]
    return json.dumps(nodes)
```

@knikolla was using this script:

```python
import subprocess
import ast
import sys

def find_node(query):
    p_cmd = subprocess.Popen("haas list_projects", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    project_lines = p_cmd.stdout.readlines()
    retval = p_cmd.wait()

    projects = ast.literal_eval(project_lines[0])
    for project in projects:
        n_cmd = subprocess.Popen("haas list_project_nodes " + project, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        node_lines = n_cmd.stdout.readlines()
        nodes = ast.literal_eval(node_lines[0])
        for node in nodes:
            if node == query:
                print project
	        return

if __name__ == '__main__':
    find_node(sys.argv[1])
```

**Comment by zenhack** [comment]
Yeah, it was pretty apparent that that's what's going on. As in the original description, we're being sloppy all over. The right solution here (and the one the sqlalchemy docs recommend) is the one I mention up top --- we should just have the session be a request-local variable, and set it up/tear it down somewhere `haas.rest.request_handler()`. @henn, Does this make sense to you?

As a side note, it might be worthwhile to consider migrating things back to flask. We got rid of it because we weren't using much of what it provided, but we're re-inventing more and more. The sqlalchemy integration just does this for you, for example. It could be done piecemeal; If you guys think it's worth it I can outline the approach I'd take with that.

Also, @henn, would you assign this issue to me? Talked with @okrieg, and the plan is for me to fix it.

**Comment by henn** [comment]
@zenhack: assigned. Thanks for taking this on!

Re: request-local, that sounds wonderful.

Re: flask, how much effort do you think that would be? Could you see it impacting the WSGI config, py.test or anything else?

**Comment by zenhack** [comment]
The main thing is it can replace most of the goop in haas.rest. we can also someday simplify the dB stuff... I'm just seeing us building more and more ourselves that we could just pull from there.

Step one would be fairly non intrusive, and replace most (but not all) of the logic in haas.rest. other bits could be ported over in pieces, so it doesn't need to divert major development efforts.

**Comment by zenhack** [comment]
Status update: I've got a branch up on my fork that has a test that catches the leak. It only occurs on postgres, not surprising that sqlite doesn't have a connection limit.
