### ISSUE TITLE
API support for pre-selecting a VLAN for a network

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#459]
A very useful feature would be for administrators to have the ability through the API to create a network within a project that is assigned to a particular VLAN ID.

This would be useful for allowing projects to communicate from 2 different HaaS installations that have a shared VLAN domain; it's a problem I am encountering now in terms of trying to span a single HaaS install.

Things we would need to discuss would be the allocation semantics: once a VLAN were manually allocated, would it be removed from the free pool? What if it were already allocated to an existing Network? If a VLAN could be allocated to 2 networks, would it not be given back to the free pool until both were returned?

Note that this could also be a solution to #409.

**Comment by zenhack** [comment]
We discussed this in person, but this already exists and has for some time. Closing.
