### ISSUE TITLE
Need to be able to allow multiple VLANs/networks for a given node/nic/port

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#47]
If we're going to be using the HaaS to deploy openstack on bare metal, need to be able to configure the network in such a way that the nodes can use multiple VLANs to communicate with eachother - Neutron makes use of this in one of the standard configurations.

The way to go about this is to set the ports to trunking, rather than access mode.

Probably step 1 is to convert the existing implementation from setting access mode (with a given VLAN), to trunking mode, with that VLAN as native (and no other VLANs assigned). From there we can start worrying about how we should expose the ability to added tagged VLANs.

**Comment by henn** [comment]
Reopening, as we have hardware now that will require this feature.

**Comment by henn** [comment]
FYI - the implementation will need to take into consideration [VLAN hopping attacks](https://en.wikipedia.org/wiki/VLAN_hopping).

**Comment by henn** [comment]
Addressed by #455
