### ISSUE TITLE
Show_switch

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#472]
Now that #455 has introduced dynamically-managed switches, we need a way to show information about them.

Useful info I can think of in `GET /switch/<switch>` would be:
* The switch type
* Every port on the switch, the NIC+Node it is connected to, and the output of `show_nic`. This could be helpful in debugging connectivity problems.

Useful info for `GET /switch` would be a list of every switch HaaS knows about (optionally recursively showing info).

**Comment by zenhack** [comment]
This came up in the comments for #447, and I mentioned a design issue around the polymorphic nature of switches. Do you have thoughts on that?

**Comment by henn** [comment]
Merging with #447.
