### ISSUE TITLE
DB ACLs

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#473]
As discussed in #455, there are certain columns (and maybe tables) for which different parts of HaaS could be restricted. Providing a default set of DB ACLs would enhance HaaS's defense in depth by taking advantage of its component architecture.

For example, the API server would only ever need permissions to write Switch credentials; it should never read them back. The Network Action Server should never need to access OBM or User tables.

This would make a good project for someone looking to learn more about how HaaS works and databases. Any of myself, @lokI8, @zenhack or @gsilvis could help.

**Comment by zenhack** [comment]
Removing the easy label; this requires a certain amount of design and a fairly complete picture of where everything is used in HaaS.

Also, this appears to be a duplicate of #460, is it not?

**Comment by henn** [comment]
Yep. Closing as a dup, though this is a little broader in nature.

I was thinking "easy" because once you understand HaaS's object model, it should be straightforward.
