### ISSUE TITLE
show_node() should display attached networks

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#499]
Currently, when attempting to detach a node from a project, one can encounter errors due to the node still being connected to networks:
```
$ haas project_detach_node moc-prod node-123
Unexpected status code: 409
Response text:
{"msg": "Node attached to a network", "type": "BlockedError"}
```

Especially if this node were set up by someone else, it can be difficult to figure out which networks it is connected to.

show_node() should display a list of such networks, as well as the channels on which they are connected. This could be implemented as a show_nic() command, which is then called within show_node() for each nic.

This is somewhat the inverse of #496.

This was encountered by several folks, including @rahulait and @weinbe2

**Comment by jmcadden** [comment]
I ran across this issue as well. This fix looks ideal.
