### ISSUE TITLE
Query interface should sort entries

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#500]
It's an optional argument to [json.dump()](https://docs.python.org/2/library/json.html#basic-usage): sort_keys

**Comment by kylehogan** [comment]
This is currently being used. Are there any places it still needs to be added or can this be closed?

**Comment by henn** [comment]
Looking through [haas/api.py](https://github.com/CCI-MOC/haas/blob/master/haas/api.py), I see:

- [ ] list_projects
- [ ] list_free_nodes
- [ ] list_project_nodes
- [ ] list_project_networks
- [ ] list_project_headnodes
- [ ] list_headnode_images

**Comment by SahilTikale** [comment]
#568 addresses it.

**Comment by ron-unrau** [comment]
Sorry to jump in after the horses have already left the barn, but what motivated this issue? Do the clients require the lists to be sorted for some reason? If some do and some don't, it's a lot more scalable to let the clients do their own sorting. If the server has to do the sorting, it's more efficient to keep the lists in sorted order so the server doesn't have to continuously sort the same list again and again for each reply.
