### ISSUE TITLE
Request nodes with certain properties

### ISSUE THREAD

**Issue by weinbe2** [CCI-MOC/haas#503]
I.e., over 4 gb of RAM, in particular interest for me is nodes with GPUs.

**Comment by henn** [comment]
Thanks for your issue!

The thought we've had on this up till now was that there would be an external inventory service that would keep track of the various attributes, like GPUs, RAM, disk space, CPUs, etc.

What do you think?

**Comment by weinbe2** [comment]
That sounds good! I briefly spoke with Ata about this, and maybe some piece of what he's doing for monitoring could be used here? Obviously we don't need constant monitoring to tell us how much RAM a node has or if it has accelerators, but maybe something of the sort?

**Comment by henn** [comment]
The implementation can be different depending on needs, but I view this as fundamentally different from monitoring (though the work being done for monitoring could potentially be used to populate such a catalog).

In an OCX environment [ref1](http://open.bu.edu/handle/2144/11427),[ref2](http://open.bu.edu/handle/2144/11214), the Service Directory would do this. In our environment, we could use the private wiki.

Based on this, I'm going to close this issue and add you to the private task we have. Please re-open if you think this belongs as an issue.
