### ISSUE TITLE
Use local.db in api.py

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#538]
In api.py (and maybe other files?), almost every method has this sort of construct:
```python
db = local.db
...
db.delete(network)
db.commit()
```

We could refactor this to use `local.db` throughout, in order to save the unnecessary `db = local.db` line in every API function.

@zenhack @SahilTikale @okrieg @pjd-nu @gsilvis: thoughts?

**Comment by zenhack** [comment]
When I wrote the code I specifically didn't do this since it was a good
bit more verbose without any real readability improvement. There are a
few cases where the variable was only used once, in which case I did
inline it. I don't think it's dramatically important either way.

**Comment by kylehogan** [comment]
what is the verdict on this? Given get_auth_backend() has the same possible issue I personally vote that it stays as is.

**Comment by zenhack** [comment]
So, `local.db` disappears with the Flask-SQLAlchemy work I'm doing anyway (#556), so this becomes moot. Turns into `db.session`, and I'm inlining it everywhere since that's consistent with what all of the examples in the Flask docs do. I recommend we close.

**Comment by kylehogan** [comment]
Closing because irrelevant post Flask-SQLAlchemy
