### ISSUE TITLE
re-integrate flask

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#540]
Flask will give us a framework that handles a bunch of stuff we're handling in a hacky way right now.

Some of this functionality includes:
* [ ] flask's URL router and argument verification
* [ ] built-in support for middleware
* [ ] flask's built-in sqlalchemy for DB sessions
* [ ] Doing calls like `get_auth_backend()` automatically (see #491)

**Comment by zenhack** [comment]
I'm going to close this, since the flask stuff has been merged.
