### ISSUE TITLE
Check HaaS master firewall rules re: vnc

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/haas#67]
The way our HaaS masters are currently configured, it may be possible for one headnode to access another's vnc console, by connecting to the host. The more general problem is that we need to make sure that with the exception of the specific services needed by the headnodes, the headnodes have no more access to the haas master than the outside world.

**Comment by henn** [comment]
I think the decision to move the headnode out of HaaS pushes this problem to whatever the external service is doing (hopefully it has plenty of capability to deal with this).

What do you think? Please feel free to reopen.
