### ISSUE TITLE
Continuous integration testing

### ISSUE THREAD

**Issue by henn** [CCI-MOC/haas#90]
We should look at setting up some sort of automated continuous testing suite.

The idea would be that a push to a particular branch (like devel or master) would trigger an automated process to pull the latest repo, run the unit tests and run some integration tests that put the drivers to work. If any of the tests hit an error, notification would be sent to either the developers list, the individual who submitted the last code change that broke the build or perhaps our IRC channel.

We could use the Cisco switch along with some of the blades we have in the lab.

The openstack project uses [Jenkins](http://jenkins-ci.org/), though [many other suites](https://en.wikipedia.org/wiki/Continuous_integration#Software) exist as well.

**Comment by henn** [comment]
FYI - it looks like there are a number of free hosted CI providers out there who integrate with github and are free for open source projects, including:

* https://travis-ci.org/
* https://semaphoreci.com

We should pick one (or two?) and go with it.

**Comment by henn** [comment]
Also, just found this: http://www.software.ac.uk/resources/guides/hosted-continuous-integration

**Comment by zenhack** [comment]
I say we go with travis. I've used it before, it's pretty straightforward.

**Comment by henn** [comment]
This is addressed by https://github.com/CCI-MOC/haas/commit/431f5aee9c7922f20371474234ac19c04f6c4c36 and 23b79fcf8e5fff2a6bac65ce090e3294ab638802.

There's still more to do (#518), but this should help.

**Comment by zenhack** [comment]
Two things:

1. We should be running `tests/stress.py` as well.
2. When did it become okay to skip code review?

**Comment by henn** [comment]
@zenhack 

Re point 1: I've added this to #518 

Re point 2: I didn't lightly decide to bypass review, but made an executive decision that we needed to ensure additional pull requests didn't break the tests without waiting the 1-2 months for review (as other PRs lately have taken). Also - it wasn't really a code change anyhow (it involved the creation of an additional file nothing else looks at, which in other CI environments would likely have lived outside the code tree).

**Comment by zenhack** [comment]
Code review taking on the order of months is a serious problem in its own right. We've always been pretty lousy at triaging this stuff, but if it's getting to the point where it's motivating us to skip code review because a change is important, that should raise some flags.

@okrieg has approved pulling me in if you guys need extra hands with the review. I'd encourage you to make use of that in favor of taking shortcuts.
